//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourOperator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ClientID { get; set; }
        public string FullName { get; set; }
        public string ContactInfo { get; set; }
        public int TourID { get; set; }
        public string Email { get; set; }
        public int ReviewID { get; set; }
        public int VoucherID { get; set; }
    
        public virtual CustomerReviews CustomerReviews { get; set; }
        public virtual Tours Tours { get; set; }
        public virtual TravelVouchers TravelVouchers { get; set; }
    }
}
