//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourOperator.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourOperatorEntities : DbContext
    {
        public TourOperatorEntities()
            : base("name=TourOperatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accountant> Accountant { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<CustomerReviews> CustomerReviews { get; set; }
        public virtual DbSet<Guides> Guides { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<StateStatisticsReports> StateStatisticsReports { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaxPayments> TaxPayments { get; set; }
        public virtual DbSet<Tours> Tours { get; set; }
        public virtual DbSet<TravelVouchers> TravelVouchers { get; set; }
    }
}
